#### This script can be used to construct the ZH-ECochG Bode Plot ####

# This R script is designed to plot the electrocochleography (ECochG) response amplitude and phase against the insertion angle and tonotopic region of cochlear implant electrodes using the ZH-ECochG Bode Plot. It also includes the pre- and postoperative audiogram on the same axes for comparison. The script has been tested using R 4.3.1.

# If you use this script, please cite the following publication: Geys, M.; Sijgers, L.; Dobrev, I.; Dalbert, A.; Röösli, C.; Pfiffner, F.; Huber, A. ZH-ECochG Bode Plot: A Novel Approach to Visualize Electrocochleographic Data in Cochlear Implant Users. J. Clin. Med. 2024, 13, 3470. https://doi.org/10.3390/jcm13123470

# We encourage users to read the publication to understand the context, implementation, and potential applications of the methods employed in this script.

# This script was developed by Marlies Geys and Leanne Sijgers, Department of Otolaryngology, Head & Neck Surgery, University Hospital Zurich, University of Zurich, Switzerland

# Please make sure all the necessary files (.xlsx) are in the same folder as the R project. 

 
#### adapt and define the parameters in this section ####

# uncomment the next two lines to install the necessary packages
# install.packages("dplyr")
# install.packages("readxl")

rm(list = ls()) # clear environment

library(dplyr) 
library(readxl)

# define output pdf file
pdf_out = "ZH-ECochG Bode Plot_Example.pdf"
pdf(file = paste(pdf_out, sep="/"))

# define the title of the figure
plot_title <- "ZH-ECochG Bode Plot"

# adapt this number to move the angle x-axis vertically
loc_axis <- 1.6 # increase to move the axis towards the bottom

# define the names of the axes files
axes_file_m <- "Example_axes_monitoring_AB.xlsx" # monitoring axes file (generated by Matlab-Script); set to none when not including monitoring data
axes_file_s <- "Example_axes_sweep_AB.xlsx" # sweep axes file (generated by Matlab-Script); set to "none" when not including sweep data

# define the names of the ECochG data files
data_file_m <- "Example_amp_phase_monitoring_AB.xlsx" # monitoring data file; set to none when not including monitoring data
data_file_si <- "Example_amp_phase_sweep_intraOP_AB.xlsx" # Intra-OP sweep data file; set to none when not including intra-OP sweep data
data_file_sp <- "Example_amp_phase_sweep_postOP_AB.xlsx" # Post-OP sweep data file; set to none when not including post-OP sweep data
display_phase_sp <- 1 # set to 0 when the postoperative phase should not be displayed, e.g., when responses are within the noise floor

# define the name of the audiogram data file
data_file_a_pre <- "Example_preoperative_audiogram.xlsx" # audiogram preoperative data file; set to none when not including preoperative data
data_file_a_post <- "Example_postoperative_audiogram.xlsx" # audiogram postoperative data file; set to none when not including preoperative data


#### load all axes and data files ####

if (file.exists(axes_file_m)) {
  df_m_a <- read_excel(axes_file_m, sheet = 1)
} 

if (file.exists(axes_file_s)) {
  df_s_a <- read_excel(axes_file_s, sheet = 1)
} 

if (file.exists(data_file_m)) {
  df_m_d <- read_excel(data_file_m, sheet = 1)
  df_m <- cbind(df_m_a, df_m_d) # combine axes and data in one dataframe
  df_m["Amplitude_dB"] <- 20 * log10(df_m$Amplitude / 1) # relative to 1uV
  df_m["Frequency_kHz"] <- df_m["Frequency (Hz)"] / 1000 # kHz
} 

if (file.exists(data_file_si)) {
  df_si_d = read_excel(data_file_si, sheet = 1)
  df_si = cbind(df_s_a, df_si_d) # combine axes and data in one dataframe
  df_si["Amplitude_dB"] = 20 * log10(df_si$Amplitude / 1) # relative to 1uV
  df_si["Frequency_kHz"] = df_si["Frequency (Hz)"] / 1000 # kHz
  df_si <- na.omit(df_si)
} 

if (file.exists(data_file_sp)) {
  df_sp_d = read_excel(data_file_sp, sheet = 1)
  df_sp = cbind(df_s_a, df_sp_d) # combine axes and data in one dataframe
  df_sp["Amplitude_dB"] = 20 * log10(df_sp$Amplitude / 1) # relative to 1uV
  df_sp["Frequency_kHz"] = df_sp["Frequency (Hz)"] / 1000 # kHz
  df_sp <- na.omit(df_sp)
} 

if (file.exists(data_file_a_pre)) {
  df_a_pre = read_excel(data_file_a_pre, sheet = 1)
  df_a_pre["Frequency"] = df_a_pre["Frequency"] / 1000 # kHz
} 

if (file.exists(data_file_a_post)) {
  df_a_post = read_excel(data_file_a_post, sheet = 1)
  df_a_post["Frequency"] = df_a_post["Frequency"] / 1000 # kHz
} 

#### define parameters ####

custom_ticks <- c(0.25, 0.5, 1, 2, 4, 8, 16) # frequency tick marks on the x-axis
max_x = 20 # maximum frequency value on the x-axis
linew = 3 # line width
mycol <- rgb(0.128, 0.128, 0.128, alpha = 0.1)


#### define min and max of y-scale ####

# default values
ymin = -11 
ymax = 40

# expand the axes when needed
if (exists('df_m')) { 
  ymin <- min(ymin, df_m$Amplitude_dB, na.rm = T)
  ymax <- max(ymax, df_m$Amplitude_dB, na.rm = T)
}
if (exists('df_si')) { 
  ymin <- min(ymin, df_si$Amplitude_dB, na.rm = T)
  ymax <- max(ymax, df_si$Amplitude_dB, na.rm = T)
}
if (exists('df_sp')) { 
  ymin <- min(ymin, df_sp$Amplitude_dB, na.rm = T)
  ymax <- max(ymax, df_sp$Amplitude_dB, na.rm = T)
}


#### define functions for plotting the amplitude ####

myplot <- function(x, y, linetype) {
  plot(x, y, 
       log = "x", xaxt = "n",  pch = 16, type = "o", lty = linetype,
       xlab = "", ylab = "Amplitude (dB re: 1µV)", 
       xlim = c(min(custom_ticks), max_x), ylim = c(ymin, ymax), 
       col = "orange", lwd = linew, bty = "n", las=1) 
}

myline <- function(x, y, linetype) {
  lines(x, y, 
        log = "x", xaxt = "n",  pch = 16, type = "o", lty = linetype, 
        xlab = "", ylab = "Amplitude (dB re: 1µV)", 
        xlim=c(min(custom_ticks), max_x), ylim = c(ymin, ymax), 
        col = "orange", lwd = linew, bty = "n")
}


#### make amplitude plot (top) ####

leg <- c() # legend names
cols <- c() # legend colors
linet <- c() # legend linetypes

par(mfrow = c(2,1), mar = c(0, 3, 5, 3) + 1.2, xpd=TRUE)    

if (exists('df_m')) { 
  
  myplot(df_m$Frequency_kHz, df_m$Amplitude_dB, linetype = "solid") 
  leg <- c(leg, "Intra-OP amplitude, monitoring")
  cols <- c(cols, "orange")
  linet <- c(linet, "solid")
  
  if (exists('df_si')) { 
    
    myline(df_si$Frequency_kHz, df_si$Amplitude_dB, linetype = "dashed") 
    leg <- c(leg, "Intra-OP amplitude, sweep")
    cols <- c(cols, "orange")
    linet <- c(linet, "dashed")
    
  } 
  
  if (exists('df_sp')) { 
    
    myline(df_sp$Frequency_kHz, df_sp$Amplitude_dB, linetype = "dotted") 
    leg <- c(leg, "Post-OP amplitude, sweep")
    cols <- c(cols, "orange")
    linet <- c(linet, "dotted")
    
  } 
  
} else if (exists('df_si')) { 
  
  myplot(df_si$Frequency_kHz, df_si$Amplitude_dB, linetype = "dashed") 
  leg <- c(leg, "Intra-OP amplitude, sweep")
  cols <- c(cols, "orange")
  linet <- c(linet, "dashed")
  
  if (exists('df_sp')) { 
    
    myline(df_sp$Frequency_kHz, df_sp$Amplitude_dB, linetype = "dotted") 
    leg <- c(leg, "Post-OP amplitude, sweep")
    cols <- c(cols, "orange")
    linet <- c(linet, "dotted")
    
  } 
  
} else if (exists('df_sp')) { 
  
  myplot(df_sp$Frequency_kHz, df_sp$Amplitude_dB, linetype = "dotted") 
  leg <- c(leg, "Post-OP amplitude, sweep")
  cols <- c(cols, "orange")
  linet <- c(linet, "dotted")
  
} 

abline(h = 0, col = "grey", lty = "dashed", xpd = FALSE)
title(plot_title, line = 5)


#### Audiogram on amplitude plot (top) ####

if (exists('df_a_pre')) { 
  par(new = TRUE)                            
  plot(df_a_pre$Frequency, df_a_pre$Threshold, log = "x", xaxt = "n", 
       xlim = c(min(custom_ticks), max_x), ylim = rev(range(0,120)), 
       type = "l", col = mycol, lwd = linew,          
       axes = FALSE, xlab = "", ylab = "")
  points(df_a_pre$Frequency, df_a_pre$Threshold, pch = 4, col = "black", cex = 1)
  axis(side = 4, las = 1, col.axis = "darkgrey") # add right axis    
  mtext("Hearing Threshold (dBHL)", side = 4, col = "darkgrey", line = 3)  
  
  leg <- c(leg, "Pre-OP audiogram")
  cols <- c(cols, mycol)
  linet <- c(linet, "solid")
}

if (exists('df_a_post')) { 
  par(new = TRUE)                            
  plot(df_a_post$Frequency, df_a_post$Threshold, log = "x", xaxt = "n", 
       xlim = c(min(custom_ticks), max_x), ylim = rev(range(0,120)), 
       type = "l", lty=2, col = mycol, lwd = linew,          
       axes = FALSE, xlab = "", ylab = "")
  points(df_a_post$Frequency, df_a_post$Threshold, pch = 4, col = "black", cex = 1)
  axis(side = 4, las = 1, col.axis = "darkgrey") # add right axis    
  mtext("Hearing Threshold (dBHL)", side = 4, col = "darkgrey", line = 3)  
  
  leg <- c(leg, "Post-OP audiogram")
  cols <- c(cols, mycol)
  linet <- c(linet, "dashed")
}

legend("topright", inset = c(-0.15, -0.55), # make legend
       legend = leg, 
       col = cols, 
       lty = linet, 
       lwd = linew, 
       bty = "n")

#### Add background vertical lines ####

v_lines <- custom_ticks
for (line in v_lines) {
  abline(v = line, col = "lightgray", lty = "solid", xpd = FALSE)
}


#### Define min and max of y-scale ####

ymin = 1e6
ymax = -1e6

if (exists('df_m')) { 
  ymin <- min(ymin, df_m$Phase, na.rm = T)
  ymax <- max(ymax, df_m$Phase, na.rm = T)
}
if (exists('df_si')) { 
  ymin <- min(ymin, df_si$Phase, na.rm = T)
  ymax <- max(ymax, df_si$Phase, na.rm = T)
}
if (exists('df_sp')) { 
  ymin <- min(ymin, df_sp$Phase, na.rm = T)
  ymax <- max(ymax, df_sp$Phase, na.rm = T)
}

custom_ticks_phase <- seq(round(ymin / 180) * 180, round(ymax / 180) * 180, by = 180)


#### define functions for plotting the phase ####
myplotp <- function(x, y, linetype) {
  plot(x, y, 
       xaxt = "n", yaxt = "n",  log = "x", pch = 16, type = "o", lty = linetype,
       xlab = "", ylab = "Phase (°)", 
       xlim = c(min(custom_ticks), max_x), 
       ylim = c(ymin, ymax), 
       col = "lightblue", lwd = linew, bty = "n")             
}

mylinep <- function(x, y, linetype) {
  lines(x, y, 
        xaxt = "n", yaxt = "n",  pch = 16, type = "o", lty = linetype, 
        xlab = "", ylab = "Phase (°)", 
        xlim = c(min(custom_ticks), max_x), 
        ylim = c(ymin, ymax), 
        col = "lightblue", lwd = linew, bty = "n")             
}


#### make phase plot (bottom) ####

par(mar=c(5.5, 3, 2, 3) + 1.2, xpd=TRUE) # location of subplot

leg_p <- c() # legend
cols_p <- c() # colors
linet_p <- c() # linetypes

if (exists('df_m')) { 
  
  myplotp(df_m$Frequency_kHz, df_m$Phase, linetype = "solid") 
  leg_p <- c(leg_p, "Intra-OP phase, monitoring")
  cols_p <- c(cols_p, "lightblue")
  linet_p <- c(linet_p, "solid")
  
  if (exists('df_si')) { 
    
    mylinep(df_si$Frequency_kHz, df_si$Phase, linetype = "dashed") 
    leg_p <- c(leg_p, "Intra-OP phase, sweep")
    cols_p <- c(cols_p, "lightblue")
    linet_p <- c(linet_p, "dashed")
    
  } 
  
  if (exists('df_sp') && display_phase_sp) { 
    
    mylinep(df_sp$Frequency_kHz, df_sp$Phase, linetype = "dotted") 
    leg_p <- c(leg_p, "Post-OP phase, sweep")
    cols_p <- c(cols_p, "lightblue")
    linet_p <- c(linet_p, "dotted")
    
  } 
  
} else if (exists('df_si')) { 
  
  myplotp(df_si$Frequency_kHz, df_si$Phase, linetype = "dashed") 
  leg_p <- c(leg_p, "Intra-OP phase, sweep")
  cols_p <- c(cols_p, "lightblue")
  linet_p <- c(linet_p, "dashed")
  
  if (exists('df_sp') && display_phase_sp) { 
    
    mylinep(df_sp$Frequency_kHz, df_sp$Phase, linetype = "dotted") 
    leg_p <- c(leg_p, "Post-OP phase, sweep")
    cols_p <- c(cols_p, "lightblue")
    linet_p <- c(linet_p, "dotted")
    
  } 
  
} else if (exists('df_sp') && display_phase_sp) { 
  
  myplotp(df_sp$Frequency_kHz, df_sp$Phase, linetype = "dotted") 
  leg_p <- c(leg_p, "Post-OP phase, sweep")
  cols_p <- c(cols_p, "lightblue")
  linet_p <- c(linet_p, "dotted")
  
} 

abline(h = 0, col = "grey", lty = "dashed", xpd = FALSE)
title(plot_title, line = 5)

axis(side = 2, at = custom_ticks_phase, labels = custom_ticks_phase, 
     tick = TRUE, las = 1)

# Add minor tick marks
axis(side = 2, at = seq(floor(ymin / 90) * 90, ceiling(ymax / 90) * 90, by = 90), 
     labels = FALSE, tcl = -0.25)

# Add background vertical lines
for (line in v_lines) {
  abline(v = line, col = "lightgray", lty = "solid", xpd = FALSE)
}

# add legend
legend("topright", inset = c(-0.15, -0.45), 
       legend = leg_p, 
       col = cols_p, 
       lty = linet_p, 
       lwd = linew, 
       bty = "n")

# add x-axis
axis(side = 1, at = custom_ticks, labels = custom_ticks, tick = TRUE)

# Add a second x-axis with insertion angle
insertion_angle_ticks <- seq(-90, 600, by = 30)
if (exists('df_m')) { 
  labels_at <- approx(df_m$`Angle (degrees)`, 
                      df_m$Frequency_kHz, xout = insertion_angle_ticks)$y
} else if (exists('df_si')) { 
  labels_at <- approx(df_si$`Angle (degrees)`, 
                      df_si$Frequency_kHz, xout = insertion_angle_ticks)$y
} else if (exists('df_sp')) { 
  labels_at <- approx(df_sp$`Angle (degrees)`, 
                      df_sp$Frequency_kHz, xout = insertion_angle_ticks)$y
}
labels_at_2 <- labels_at[c(TRUE, FALSE, FALSE)]
ins_ticks <- insertion_angle_ticks[c(TRUE, FALSE, FALSE)]
axis(side = 1, at = labels_at_2, labels = ins_ticks, 
     tick = TRUE, pos = c(ymin * loc_axis, 0))
axis(side = 1, at = labels_at, labels = FALSE, 
     tcl = -0.25, pos = c(ymin * loc_axis, 0))
mtext("Insertion angle (°)", side = 1, col = "black",line = 5.5, las=0)
mtext("Tonotopic Region (kHz)", side = 1, col = "black",line = 2, las=0)

dev.off()